version: '3.7'

services:
    mongo_db:
        image: mongo:6.0
        container_name: mongo_db_container
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db
    
    spring_boot_docker:
        build: .
        container_name: spring_boot_docker_container
        ports:
            - 7000:8080
        depends_on:
            - mongo_db
        environment:
            SPRING_DATA_MONGODB_URI: "mongodb://mongo_db:27017/spring"

volumes:
  mongo_data:





